#!/usr/bin/env bash
# Bash script to display listening ports

# Check if script is run with sudo/root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root or with sudo"
    exit 1
fi

# Show TCP and UDP listening sockets
netstat -lp | head -n2
netstat -lp | tail -n +3 | grep -v "127.0.0.1\|::1" | grep -E "(LISTEN|^udp)"


echo ""

# Show UNIX domain listening sockets
netstat -xlpn | head -n2
netstat -xlpn | tail -n +3 | grep LISTEN 
