#!/usr/bin/env bash
# This is a script to ping an IP address

# Check if IP address argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS="$1"

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
